apiVersion: v1
kind: Namespace
metadata:
  name: kyukei-panda
  labels:
    name: kyukei-panda
    environment: production
    app: kyukei-panda
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyukei-panda-config
  namespace: kyukei-panda
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "info"
  DB_CONNECTION: "pgsql"
  DB_PORT: "5432"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  BROADCAST_DRIVER: "pusher"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: kyukei-panda-secrets
  namespace: kyukei-panda
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  APP_KEY: YmFzZTY0X2VuY29kZWRfYXBwX2tleQ==
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ==
  DB_DATABASE: a3l1a2VpX3BhbmRh
  DB_USERNAME: a3l1a2VpX3VzZXI=
  DB_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk
  REDIS_HOST: cmVkaXMtc2VydmljZQ==
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
  PUSHER_APP_ID: cHVzaGVyX2FwcF9pZA==
  PUSHER_APP_KEY: cHVzaGVyX2FwcF9rZXk=
  PUSHER_APP_SECRET: cHVzaGVyX2FwcF9zZWNyZXQ=
  PUSHER_APP_CLUSTER: bXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyukei-panda-app
  namespace: kyukei-panda
  labels:
    app: kyukei-panda-app
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kyukei-panda-app
  template:
    metadata:
      labels:
        app: kyukei-panda-app
        tier: frontend
    spec:
      containers:
      - name: kyukei-panda
        image: kyukei-panda:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: kyukei-panda-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: kyukei-panda-config
              key: APP_DEBUG
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: kyukei-panda-secrets
              key: APP_KEY
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: kyukei-panda-config
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: kyukei-panda-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: kyukei-panda-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: kyukei-panda-secrets
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: kyukei-panda-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kyukei-panda-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: kyukei-panda-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: kyukei-panda-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kyukei-panda-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/ping
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage
        - name: cache-volume
          mountPath: /var/www/html/bootstrap/cache
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: kyukei-panda-storage-pvc
      - name: cache-volume
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kyukei-panda-service
  namespace: kyukei-panda
  labels:
    app: kyukei-panda-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: kyukei-panda-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyukei-panda-storage-pvc
  namespace: kyukei-panda
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kyukei-panda-ingress
  namespace: kyukei-panda
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - kyukei-panda.com
    - www.kyukei-panda.com
    secretName: kyukei-panda-tls
  rules:
  - host: kyukei-panda.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kyukei-panda-service
            port:
              number: 80
  - host: www.kyukei-panda.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kyukei-panda-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kyukei-panda-hpa
  namespace: kyukei-panda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyukei-panda-app
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
